# Generated by Django 5.1.7 on 2025-03-26 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='product',
            new_name='game_product',
        ),
    ]
